<?php

namespace HUB\ChiffredMessengerBundle\Repository;

/**
 * CommunicatingEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunicatingEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
