CategoryList = [
    {id: 0, name: "agriculture", label: "Agriculture et élevage", img: "/images/categories/agriculture.png"},
    {id: 1, name: "art", label: "Arts", img: "/images/categories/art.png"},
    {id: 2, name: "childcare", label: "Enfance", img: "/images/categories/childcare.png"},
    {id: 3, name: "construction", label: "Chantier et construction", img: "/images/categories/construction.png"},
    {id: 4, name: "craft_work", label: "Artisanat et services", img: "/images/categories/craft_work.png"},
    {id: 5, name: "digital", label: "Numérique", img: "/images/categories/digital.png"},
    {id: 6, name: "events", label: "Événementiel", img: "/images/categories/events.png"},
    {id: 7, name: "food", label: "Restauration", img: "/images/categories/food.png"},
    {id: 8, name: "healthcare", label: "Santé", img: "/images/categories/healthcare.png"},
    {id: 9, name: "journalism", label: "Journalisme", img: "/images/categories/journalism.png"},
    {id: 10, name: "knowledge_acces", label: "Circulation des savoirs", img: "/images/categories/knowledge_acces.png"},
    {id: 11, name: "lodging", label: "Hébergement et habitat", img: "/images/categories/lodging.png"},
    {id: 12, name: "logistic_and_transport", label: "Logistique et transport", img: "/images/categories/logistic_and_transport.png"},
    {id: 13, name: "manufacturing", label: "Production", img: "/images/categories/manufacturing.png"},
    {id: 14, name: "militancy", label: "Militantisme", img: "/images/categories/militancy.png"},
    {id: 15, name: "science_and_research", label: "Sciences et recherche", img: "/images/categories/science_and_research.png"},
    {id: 16, name: "service_and_maintenance", label: "Mécanique et entretien", img: "/images/categories/service_and_maintenance.png"},
    {id: 17, name: "solidarity", label: "Solidarité", img: "/images/categories/solidarity.png"},
    {id: 18, name: "sport_and_leisure", label: "Sport et loisir", img: "/images/categories/sport_and_leisure.png"},
    {id: 19, name: "supply_chain", label: "Distribution", img: "/images/categories/supply_chain.png"},
]