<?php

namespace ProjectBundle\Repository;

/**
 * InvitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $id
     * id de l'élement sur lequel on se réfere
     * @param $status
     * status de l'invitation : sans réponse => 0 , acceptée => 1 , refusée => 2
     * @param $is_demanded_by_project
     * true => il faut renvoyer les invit ayant pour projet projet.id
     * false => il faut renvoyer les invit ayant pour user user.id
     * @return array
     */
    public function invitationsByStatus($id, $status, $is_demanded_by_project)
    {
        $qb = $this->createQueryBuilder('a');
        if($is_demanded_by_project) {
            $qb->where('a.project = :project')
                ->setParameter('project', $id)
                ->andWhere('a.status = :status')
                ->setParameter('status', $status)
             //   ->orderBy('a.send_at', 'DESC') Todo : débugger l'ordonnage par date
            ;
        }else{
            $qb->where('a.user = :user')
                ->setParameter('user', $id)
                ->andWhere('a.status = :status')
                ->setParameter('status', $status)
              //  ->orderBy('a.send_at', 'DESC')Todo : débugger l'ordonnage par date
            ;
        }

        return $qb
            ->getQuery()
            ->getResult();
    }
}
