<?php

namespace ProjectBundle\Repository;

/**
 * UserProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
