<?php

namespace CoreBundle\Repository;

/**
 * GeolocalizedEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeolocalizedEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
