categoryLits = [
    {name: "agriculture", label: "Agriculture et élevage", img: "/images/categories/agriculture.png"},
    {name: "art", label: "Artistique", img: "/images/categories/art.png"},
    {name: "childcare", label: "Enfance", img: "/images/categories/childcare.png"},
    {name: "construction", label: "Chantier et construction", img: "/images/categories/agriculture.png"},
    {name: "craft_work", label: "Artisanat", img: "/images/categories/craft_work.png"},
    {name: "digital", label: "Agriculture/élevage", img: "/images/categories/digital.png"},
    {name: "agriculture", label: "Agriculture/élevage", img: "/images/categories/agriculture.png"},
    {name: "agriculture", label: "Agriculture/élevage", img: "/images/categories/agriculture.png"},
    {name: "agriculture", label: "Agriculture/élevage", img: "/images/categories/agriculture.png"},
    {name: "agriculture", label: "Agriculture/élevage", img: "/images/categories/agriculture.png"},
    {name: "agriculture", label: "Agriculture/élevage", img: "/images/categories/agriculture.png"},
    {name: "agriculture", label: "Agriculture/élevage", img: "/images/categories/agriculture.png"},
    {name: "agriculture", label: "Agriculture/élevage", img: "/images/categories/agriculture.png"},
    {name: "agriculture", label: "Agriculture/élevage", img: "/images/categories/agriculture.png"},
    {name: "agriculture", label: "Agriculture/élevage", img: "/images/categories/agriculture.png"},
    {name: "agriculture", label: "Agriculture/élevage", img: "/images/categories/agriculture.png"},
    {name: "agriculture", label: "Agriculture/élevage", img: "/images/categories/agriculture.png"},
    {name: "agriculture", label: "Agriculture/élevage", img: "/images/categories/agriculture.png"},
    {name: "agriculture", label: "Agriculture/élevage", img: "/images/categories/agriculture.png"},
    {name: "agriculture", label: "Agriculture/élevage", img: "/images/categories/agriculture.png"},
    {name: "agriculture", label: "Agriculture/élevage", img: "/images/categories/agriculture.png"},
    {name: "agriculture", label: "Agriculture/élevage", img: "/images/categories/agriculture.png"},

]